### ISSUE TITLE
Donor care form

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/donate-wagtail#1705]
Donor Help https://donate.mozilla.org/help/ form receives a lot of misdirected requests. Is there a way to reduce this?

## Proposed solution

- Update https://donate.mozilla.org/help/ to first show a few options supporters can choose from before revealing the form
- Working on copy and the flow in [this sheet](https://docs.google.com/spreadsheets/d/1p7dyPutO5xxLX1-uPABpFgfcNPweRqWJyz68wajKvgQ/edit#gid=0)
- Sketch from the stakeholder

![image](https://user-images.githubusercontent.com/1068783/195689931-b24d9a9e-5ee4-4734-b4f8-76a80856d9d7.png)

## Todo
- [x] Get [draft copy](https://docs.google.com/spreadsheets/d/1p7dyPutO5xxLX1-uPABpFgfcNPweRqWJyz68wajKvgQ/edit#gid=0) to better understand the flow
- [ ] Mock-up a button and a dropdown option
- [ ] Mock-up the form reveal version
- [ ] Mock-up the Thunderbird version
- [ ] Share with stakholders for feedback
- [ ] Work with dev on implementation ticket

Screen cap of existing form:
![screencapture-donate-mozilla-org-en-US-help-2022-10-13-15_52_10](https://user-images.githubusercontent.com/1068783/196481017-fb049c5a-cb79-4c45-971f-b55ddbc76e87.png)

**Comment by kristinashu** [comment]
Benchmark showing "Quick Actions" that then go to a new page with the drop down and form:

<img width="1370" alt="Screen Shot 2022-10-17 at 8 42 41 AM" src="https://user-images.githubusercontent.com/1068783/196480639-e8839327-0353-4f3e-b926-1d25a0c8bf2c.png">


Benchmark showing a drop down that, once selected, updates the same page with content below.

<img width="1417" alt="Screen Shot 2022-10-17 at 8 42 19 AM" src="https://user-images.githubusercontent.com/1068783/196480559-0b2d45ba-2188-4b77-8453-0b151390d119.png">
<img width="1374" alt="Screen Shot 2022-10-17 at 8 42 28 AM" src="https://user-images.githubusercontent.com/1068783/196480589-708fbe60-cb70-48a6-b79b-733b97a5ed2d.png">

**Comment by kristinashu** [comment]
I’ve created some very quick pages in the CMS for both a donate landing page and a donate help page. These are very rough and only contain placeholder text and images. Some functionality will need to be built so I’ve just used placeholder images for now to give us a better sense of what the pages would be.

Donate landing page
- Sunset [donate.mozilla.org](http://donate.mozilla.org/) and redirect it to [foundation.mozilla.org/donate/](http://foundation.mozilla.org/donate/) for better SEO, analytics, and testing
- This page would use FRU widget similar to https://onemind.org/donate/

Contact form updates
- Merge FAQ with Contact/Help
- Sunset [donate.mozilla.org/help/](http://donate.mozilla.org/help/) and redirect it to https://foundation.mozilla.org/donate/help/
- Page layout
  - Key redirects at the top
  - FAQ to help weed out questions people might use the form to ask
  -  Drop down with options
  - The Salesforce form will appear below the drop down once an option has been selected

Waiting for feedback from stakeholders.
